version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=login_system
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=login_system
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

volumes:
  mysql_data:
