CREATE DATABASE tanzima_academiclab;

CREATE TABLE ADMIN(
    NAME VARCHAR(50),
    MOBILE_NUMBER INTEGER(11) PRIMARY KEY,
    PASSWORD INTEGER(11) UNIQUE 

)

CREATE TABLE EDUCATION(
    INSTITUTE VARCHAR(50),
    DEGREE VARCHAR(50),
    PERSONID INTEGER(11) FOREIGN KEY REFERENCE ADMIN(MOBILE_NUMBER)
    
)

CREATE TABLE RESEARCH_GROUP(
    PERSONID INTEGER(10) PRIMARY KEY,
    NAME VARCHAR(50),
    EMAIL VARCHAR(20) ,
    INSTITUTE VARCHAR(50) FOREIGN KEY REFERENCE EDUCATION(INSTITUTE),
    DEGREE VARCHAR(50) FOREIGN KEY REFERENCE EDUCATION(DEGREE)
    
)

